# Generated by Django 4.2.7 on 2026-01-16 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for the API key", max_length=100
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("requests_per_minute", models.IntegerField(default=10)),
                ("requests_per_day", models.IntegerField(default=1000)),
                ("total_requests", models.BigIntegerField(default=0)),
                ("total_tokens", models.BigIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("can_chat_completions", models.BooleanField(default=True)),
                ("can_embeddings", models.BooleanField(default=True)),
                ("can_moderations", models.BooleanField(default=True)),
                ("can_images", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKeyUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("chat_completions", "Chat Completions"),
                            ("embeddings", "Embeddings"),
                            ("moderations", "Moderations"),
                            ("images_generations", "Image Generations"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("tokens_input", models.IntegerField(default=0)),
                ("tokens_output", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(max_length=100, unique=True)),
                (
                    "response_time_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                ("status_code", models.IntegerField()),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="api_keys.apikey",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key Usage",
                "verbose_name_plural": "API Key Usage Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RateLimitTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("requests_count", models.IntegerField(default=0)),
                (
                    "window_type",
                    models.CharField(
                        choices=[("minute", "Minute"), ("day", "Day")], max_length=10
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_limits",
                        to="api_keys.apikey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Limit Tracker",
                "verbose_name_plural": "Rate Limit Trackers",
                "unique_together": {("api_key", "window_start", "window_type")},
            },
        ),
    ]
