# Generated by Django 4.2.7 on 2026-01-17 10:41

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_storedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='file',
            field=models.FileField(upload_to=dashboard.models.upload_to_uuid),
        ),
    ]
